### ISSUE TITLE
hope to add a feature which can cancel the delay trigger

### ISSUE THREAD

**Issue by Yann-Wang** [ethanselzer/react-hover-observer#3]
For example, there is a situation that it will trigger a popover when the mouse is over an element more than 500ms. But if less than 500ms, the popover won't be triggered.

Looking forward to your response.

**Comment by ethanselzer** [comment]
Hi @Yann-Wang - Thanks for opening this issue. I think if you set `hoverDelayInMs` to 500, react-hover-observer will not activate until 500ms has elapsed. Here is a [live example](http://codepen.io/ethanselzer/pen/KmJXLR) you can experiment with. Does that work for your requirements.?

**Comment by ethanselzer** [comment]
@Yann-Wang - I'm closing this issue because it has been inactive. Please reopen it if you need to.
