### ISSUE TITLE
delay before triggerring a function

### ISSUE THREAD

**Issue by Sashkan** [ethanselzer/react-hover-observer#5]
I'd like to change my component state when a child component is hovered, after a short delay.

I thought 
```js


  onHoverChanged() {
    alert('toto')
    this.setStarte({hovered: true})
  }

<ReactHoverObserver
  onMouseOver={this.onHoverChanged}
   hoverDelayInMs={200}
 >
```

would do the trick, but it fires the onMouseOver function immediately ('toto' appears right as I hover the element) . How can I apply the delay ?

**Comment by ethanselzer** [comment]
Hi @Sashkan, Thanks for opening this issue. react-hover-observer was designed primarily to service the use case of notifying child components of hover state. The onMouseEnter, onMouseLeave, onMouseOver, and onMouseOut props are intended to allow for customizing the behavior of those events, not listening for the event. It is a little confusing, sorry about that. I think the prop you may be looking for is `onHoverChanged`. There is an [example of using this feature](https://codepen.io/ethanselzer/pen/MmLmYE). Also please see the [other examples](https://github.com/ethanselzer/react-hover-observer#demo), which may provide insight into react-hover-observer.

**Comment by ethanselzer** [comment]
Hi @Sashkan - I'm closing this issue because it has been inactive. Please reopen it if you need to.
